# Generated by Django 3.0.2 on 2020-01-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0003_auto_20200115_0559'),
        ('alcohol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('date', models.TimeField(null=True)),
                ('drunken', models.CharField(choices=[('drunken', '3volume'), ('So_so', '1volume'), ('not_drunken', '0.5volume')], default='not_drunken', max_length=50)),
                ('hangover', models.CharField(choices=[('too_bad', 'want_to_die'), ('so_so', 'need_to_eat'), ('great', 'nothing')], default='great', max_length=50)),
                ('alcohol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcohol.Alcohol')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_record', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_record', to='image.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
