# Generated by Django 3.0.2 on 2020-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.CharField(max_length=300, null=True)),
                ('date', models.TimeField(null=True)),
                ('drunken_level', models.CharField(choices=[('drunken', '3volume'), ('So_so', '1volume'), ('not_drunken', '0.5volume')], default='not_drunken', max_length=50)),
                ('hangover_level', models.CharField(choices=[('too_bad', 'want_to_die'), ('so_so', 'need_to_eat'), ('great', 'nothing')], default='great', max_length=50)),
                ('action_type', models.CharField(choices=[('die', 'die'), ('good', 'good'), ('heaven', 'heaven')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
