# Generated by Django 3.0.2 on 2020-01-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='profile', verbose_name='프로필 이미지'),
        ),
    ]
