# Generated by Django 3.0.2 on 2020-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0002_auto_20200220_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholrecord',
            name='bottles',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alcoholrecord',
            name='glasses',
            field=models.FloatField(null=True),
        ),
    ]
