# Generated by Django 3.0.2 on 2020-01-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0004_alcoholrecord_alcohol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcoholrecord',
            name='alcohol',
        ),
        migrations.AddField(
            model_name='alcoholrecord',
            name='alcohol_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alcohol_record', to='alcohols.Alcohol'),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='Alcohol_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alcohol', to='alcohols.AlcoholType'),
        ),
    ]
