# Generated by Django 3.0.2 on 2020-01-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0005_auto_20200122_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholrecord',
            name='alcohol_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alcohol_records', to='alcohols.Alcohol'),
        ),
    ]
