# Generated by Django 3.0.2 on 2020-01-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohols', '0006_auto_20200123_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alcoholrecord',
            old_name='alcohol_record',
            new_name='alcohol_records',
        ),
    ]
