# Generated by Django 3.0.2 on 2020-02-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_diary_creator'),
        ('alcohols', '0007_auto_20200123_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholrecord',
            name='diary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alcohol_records', to='diaries.Diary'),
        ),
    ]
