# Generated by Django 3.0.2 on 2020-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200304_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='image_photos', verbose_name='메인 이미지'),
        ),
    ]
